---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudkart
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: prachiii123/prachi-backend:latest

          ports:
            - containerPort: 5000
              protocol: TCP

          env: 
            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"
            
            - name: DB_USER
              value: admin

            - name: DB_PASSWORD
              value: password
            
            - name: DB_NAME
              value: productsdb
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 30