---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudkart
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: prachiii123/prachi-frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
            
