name: CloudKart CI/CD Pipeline

on:
  push:
    branches:
      - main

  # workflow_dispatch:
    

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js 24
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # # Validate Docker Compose File
      # - name: Validate Docker Compose
      #   run: docker compose config

      # Login to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build \
          -t ${{ vars.DOCKER_USERNAME }}/prachi-frontend:latest \
          ./Frontend

      # Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build \
          -t ${{ vars.DOCKER_USERNAME }}/prachi-backend:latest \
          ./Backend

      # Push Frontend Docker Image
      - name: Push Frontend Image
        run: |
          docker push \
          ${{ vars.DOCKER_USERNAME }}/prachi-frontend:latest

      # Push Backend Docker Image
      - name: Push Backend Image
        run: |
          docker push \
          ${{ vars.DOCKER_USERNAME }}/prachi-backend:latest


      #  # Start Full 3-Tier Application
      # - name: Run Docker Compose
      #   run: docker compose up -d

      # # Verify Running Containers
      # - name: Check Containers
      #   run: docker ps

      # # Backend Health Check
      # - name: Test Backend Health
      #   run: curl http://localhost:5000/health