# name: 3-Tier Application CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Datavase Image
      - name: Build Database Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/database:latest ./Database

      # Push Frontend Image
      - name: Push Database Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/}/database:latest

      # Build Frontend Image
      - name: Build Frontend Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/frontend:latest ./Frontend

      # Push Frontend Image
      - name: Push Frontend Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/frontend:latest

      # Build Backend Image
      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/backend:latest ./Backend

      # Push Backend Image
      - name: Push Backend Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/backend:latest


  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Deploy To EC2 Server
  #       uses: appleboy/ssh-action@v1.0.3

  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.EC2_SSH_KEY }}

  #         script: |

  #           cd ~/your-project-folder

  #           # Pull latest images
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

  #           # Restart application
  #           docker compose down
  #           docker compose up -d

  #           # Cleanup unused images
  #           docker image prune -f